### ISSUE TITLE
JWT Validate is failing with 'TypeError: authorization.replace is not a function'

### ISSUE THREAD

**Issue by bakert-ibm** [ibm-apiconnect/apigateway-experimental#26]
```
20170818T155151.289Z [apiconnect][0x85800007][gatewayscript][error] apigw(tkgw): tid(21729)[request][172.21.0.1] gtid(84c8154959970d17000054e1): GatewayScript processing Error 'TypeError: authorization.replace is not a function
In file 'internal:///jwt-validate.js' line:63, stack:TypeError: authorization.replace is not a function
    at Object.<anonymous> (internal:///jwt-validate.js:63:30)
    at Script.execute (gatewayscript:///datapower.js:158:24)
    at Object.<anonymous> (gatewayscript:///datapower.js:569:55)'
20170818T155151.289Z [apiconnect][0x80c00009][multistep][error] apigw(tkgw): tid(21729)[request][172.21.0.1] gtid(84c8154959970d17000054e1): request rule_ebc2b307ce812532631a4fb0a880c088 #3 assembly jwt-validate: Performed the assembly validate JWT action. failed: The assembly validate JWT action failed.
20170818T155151.289Z [apiconnect][0x88c00023][apigw][error] apigw(tkgw): tid(21729)[request][172.21.0.1] gtid(84c8154959970d17000054e1): Assembly rule 'rule_ebc2b307ce812532631a4fb0a880c088' is interrupted: The assembly validate JWT action failed..
```

**Comment by nctjsmith** [comment]
Here is Tim's Swagger doc:

```
swagger: '2.0'
info:
  x-ibm-name: uc1-apigwy
  title: UC1 New API Gateway Service
  version: 1.0.0
schemes:
  - https
host: $(catalog.host)
basePath: /uc1-new-api-gateway-service
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - set-variable:
          title: set_hmac_keys
          actions:
            - value: '{ "alg": "HS256",   "kty": "oct",   "use": "sig",   "k": "o5yErLaE-dbgVpSw65Rq57OA9dHyaF66Q_Et5azPa-XUjbyP0w9iRWhR4kru09aFfQLXeIODIN4uhjElYKXt8n76jt0Pjkd2pqk4t9abRF6tnL19GV4pflfL6uvVKkP4weOh39tqHt4TmkBgF2P-gFhgssZpjwq6l82fz3dUhQ2nkzoLA_CnyDGLZLd7SZ1yv73uzfE2Ot813zmig8KTMEMWVcWSDvy61F06vs_6LURcq_IEEevUiubBxG5S2akNnWigfpbhWYjMI5M22FOCpdcDBt4L7K1-yHt95Siz0QUb0MNlT_X8F76wH7_A37GpKKJGqeaiNWmHkgWdE8QWDQ",   "kid": "hs256-key" }'
              add: hs256-key
            - value: '{   "alg": "HS256",   "kty": "oct",   "use": "enc",   "k": "ZH9ThXryoyHKKphgRVFOrxywbZtU9bMjy-ypLG2Kcdo",   "kid": "hs256-enc-key" }'
              add: hs256-enc-key
          version: 1.0.0
      - gatewayscript:
          title: set_jwt_var
          version: 1.0.0
          source: "apim.setvariable('jwt', apim.getvariable('message.body'));"
      - jwt-validate:
          title: validate_jwt
          jwt: jwt
          output-claims: decoded.claims
          version: 1.0.0
          iss-claim: apic
          jwe-jwk: hs256-enc-key
          jws-jwk: hs256-key
      - gatewayscript:
          title: output_decoded.claims
          version: 1.0.0
          source: |-
            var decodedClaims = JSON.parse(apim.getvariable('decoded.claims'));
            apim.setvariable('message.body', decodedClaims.payload);
            apim.setvariable('message.headers.content-type', 'application/json');
  gateway: datapower-gateway
paths:
  /verify:
    post:
      responses:
        '200':
          description: 200 OK
      parameters:
        - name: body
          required: false
          in: body
          schema:
            type: string
          description: JWE Payload
      consumes:
        - text/plain
definitions: {}
tags: []
```

**Comment by bakert-ibm** [comment]
If I just use Gatewayscript, it works:

`var jwt = require('jwt');

var jwtToken = apim.getvariable('message.body').toString();

var decoder = new jwt.Decoder(jwtToken);

var decryptKey = {
    "alg": "HS256",
    "kty": "oct",
    "use": "enc",
    "k": "ZH9ThXryoyHKKphgRVFOrxywbZtU9bMjy-ypLG2Kcdo",
    "kid": "hs256-enc-key"
};

var verifyKey = {
    "alg": "HS256",
    "kty": "oct",
    "use": "sig",
    "k": "o5yErLaE-dbgVpSw65Rq57OA9dHyaF66Q_Et5azPa-XUjbyP0w9iRWhR4kru09aFfQLXeIODIN4uhjElYKXt8n76jt0Pjkd2pqk4t9abRF6tnL19GV4pflfL6uvVKkP4weOh39tqHt4TmkBgF2P-gFhgssZpjwq6l82fz3dUhQ2nkzoLA_CnyDGLZLd7SZ1yv73uzfE2Ot813zmig8KTMEMWVcWSDvy61F06vs_6LURcq_IEEevUiubBxG5S2akNnWigfpbhWYjMI5M22FOCpdcDBt4L7K1-yHt95Siz0QUb0MNlT_X8F76wH7_A37GpKKJGqeaiNWmHkgWdE8QWDQ",
    "kid": "hs256-key"
};

decoder.addOperation('decrypt', decryptKey)
       .addOperation('verify', verifyKey)
       .decode(function(error, claims) {
          if (error) {
              session.output.write('error validating JWT ' + error);
          } else {
              // write the JWT claims to output
              session.output.write(claims);
          }
       });`

**Comment by tonyffrench** [comment]
@nctjsmith do we have something looking at this?

**Comment by tinaho** [comment]
It's a bug for `apim.getvariable`, which returns JSON object (by default) or XML document based on Content-Type. I'll fix it in next release.

Also note that `apim` is fully backward compatible layer, it's not encouraged to use `apim` APIs. Now in gws action, we have `context` object to handle context variable, message and headers more natively. Please change the gws script as following:

``` 
// specified what kind of data you like to consume:
context.message.body.readAsBuffer(function(error, buf) {
     if (error) {
          throw error;
     } else {
          context.set("jwt", buf.toString());   // jwt expects string.
     }
})
```

With the change, it should resolve this issue.
