### ISSUE TITLE
GatewayScript session.reject is not a function

### ISSUE THREAD

**Issue by bakert-ibm** [ibm-apiconnect/apigateway-experimental#31]
I'm receiving an error in my GatewayScript stating:

`apigw (tkgw): GatewayScript processing Error 'TypeError: session.reject is not a function In file 'local://js/action_ffe463ec2fc13a6648e9ce08d80162f9.js' line:51, stack:TypeError: session.reject is not a function at Object.<anonymous> (local://js/action_ffe463ec2fc13a6648e9ce08d80162f9.js:51:31) at Script.execute (gatewayscript:///datapower.js:158:24) at Object.<anonymous> (gatewayscript:///datapower.js:569:55)'`

This same gatewayscript file works fine in traditional APIC gateway / gatewayscript.

**Comment by tinaho** [comment]
we disable session object in assembly gws action, so you cannot use all `session` APIs in assembly gws action (only `session.output.write` is provided for backward compatible).

There is an API `apim.error`, but it's only for backward compatible usage. We encourage to use another improved, more native API with the same functionality, which is in our roadmap.

**Comment by tonyffrench** [comment]
@bakert-ibm can you describe your scenario? we are looking at updating the error handling as @tinaho mentioned and the `reject` function and data used to drive the new error handling process will be associated with the new `context` object.

**Comment by bakert-ibm** [comment]
@tonyffrench - when I ran into this, I was using an existing GatewayScript which calculates a hash value and compares it to one that was provided with the original message. If the hashes do not match, I use the `session.reject` function with a message to reject the request.

If there's a different method for rejecting that should be used in APIC, that's fine with me.

The current workaround that I'm using for the API Gateway is to set a boolean variable in my GatewayScript, then in my Assembly Editor use a Switch action to check if the variable is false - then use a Throw action to throw an error. It's not the cleanest method but it does work.

**Comment by bakert-ibm** [comment]
@tinaho thank you. I've switched over to using `apim.error` in place of `session.reject` and it's working fine for now. I'll keep an eye open for the improved approach which you have stated is on the roadmap.
